before_install: 
  cd FootballTownApp

language: node_js
node_js:
- '6'
install:
- npm install
- npm install cocoapods-cli
- cd ios/
- pod install
- cd .. 
script:
- npm test

notifications:
  slack: agiledevworkspace:NnLPgZeqZmeMLZv35VWUFpWYs
