before_install: 
- cd FootballTownApp
- gem install cocoapods
before_install:
- gem install cocoapods -v '0.32.1'
- cd FootballTownApp

language: node_js
node_js:
- '6'
install:
- npm install
- cd ios/
- pod install
- cd ..
script:
- npm test

notifications:
  slack: agiledevworkspace:NnLPgZeqZmeMLZv35VWUFpWYs
