before_install: 
- cd FootballTownApp
- gem install cocoapods -v '0.32.1'

language: node_js
node_js:
- '6'
install:
- npm install
- cd ios/
- pod install
- cd .. 
script:
- npm test

notifications:
  slack: agiledevworkspace:NnLPgZeqZmeMLZv35VWUFpWYs
