# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FootballTownApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FootballTownApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end

target 'FootballTownAppTests' do
  #inherit! :search_paths

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # Pods for testing
end
